<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'JVFurigana\Module'                                 => __DIR__ . '/Module.php',
    'JVFurigana\RenderStrategy\FilterStrategy'          => __DIR__ . '/src/JVFurigana/RenderStrategy/FilterStrategy.php',
    'JVFurigana\RenderStrategy\ManualStrategy'          => __DIR__ . '/src/JVFurigana/RenderStrategy/ManualStrategy.php',
    'JVFurigana\RenderStrategy\RenderStrategyInterface' => __DIR__ . '/src/JVFurigana/RenderStrategy/RenderStrategyInterface.php',
    'JVFurigana\RubyMatch'                              => __DIR__ . '/src/JVFurigana/RubyMatch.php',
    'JVFurigana\RubyTag'                                => __DIR__ . '/src/JVFurigana/RubyTag.php',
    'JVFurigana\View\Helper\Furigana'                   => __DIR__ . '/src/JVFurigana/View/Helper/Furigana.php',
);