<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'JVFurigana\Module'               => __DIR__ . '/Module.php',
    'JVFurigana\RubyMatch'            => __DIR__ . '/src/JVFurigana/RubyMatch.php',
    'JVFurigana\RubyTag'              => __DIR__ . '/src/JVFurigana/RubyTag.php',
    'JVFurigana\RubyText'             => __DIR__ . '/src/JVFurigana/RubyText.php',
    'JVFurigana\View\Helper\Furigana' => __DIR__ . '/src/JVFurigana/View/Helper/Furigana.php',
);